[general]
import = ["~/.cache/theme/alacritty-colors.toml"]
live_config_reload = true

[colors]
# nothing here; will be overridden by import

[font]
size = 9

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[window]
padding.x = 15
padding.y = 15
decorations = "None"
opacity = 0.5
blur = true

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]
